---

- name: Set hostname
  hostname: name={{ hostname }}

- name: Update hosts file
  template: src="hosts.j2" dest="/etc/hosts"

- name: Upgrade apt packages
  apt: upgrade=safe update_cache=yes

- name: Install packages
  apt: >-
    pkg={{ item }} state=present
  with_items:
    - make  
    - curl
    - git

- name: Get rid of packages we don't want
  apt: >-
    pkg={{ item }} state=absent purge=yes
  with_items:
    - puppet
    - puppet-common
    - chef
    - chef-zero
