---

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - vorbis-tools
    - faac
    - faad
    - python-pip
    - mysql-client
    - libmysqlclient-dev
    - python2.7-dev

# Pip packages
- pip: name=setuptools extra_args='--upgrade'
- pip: requirements=/vagrant/requirements.txt

- name: Install python audiotools if necessary
  script: install-audiotools.sh

- name: Update init script for web app
  template: src="init_soundlocale.j2" dest="/etc/init.d/soundlocale"
  notify: restart webapp

- name: Set ownership and mode of web app init script
  file: path=/etc/init.d/soundlocale owner=root group=root mode=0755

- name: Symlink init script for web app
  command: update-rc.d soundlocale start 20 2 3 4 5 . stop 20 0 1 6 .
  notify: restart webapp

