---

- hosts: appservers
  remote_user: vagrant
  sudo: yes
  roles:
    - common
    - app
  vars:
    dbserver_ipaddr: 192.168.50.6
    appserver_ipaddr: 192.168.50.5
  vars_files:
    - ["vars/local.yml"]
